name: Test Workflow

on:
  push:
    branches:
      - main
      - backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==2.2.3 mediapipe==0.9.1.0 numpy==1.24.2 opencv-contrib-python==4.7.0.68 opencv-python==4.7.0.68 pickleshare==0.7.5 tensorflow==2.11.0 tensorflow-estimator==2.11.0 pytest

      - name: Test server.py
        run: |
          python -m pytest server/test_server.py
