name: Test Workflow

on:
  push:
    branches:
      - main
      - backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r server/requirements.txt

      - name: Test server.py
        uses: pytest-dev/pytest-action@v2
        with:
          path: server/test_server.py
