name: Test Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test application
        run: |
          python server/server.py &
          sleep 10s
          curl -F "file=@user_upload.mp4" http://localhost:5000/shoulder_press

      - name: Stop application
        run: |
          sudo kill $(sudo lsof -t -i:5000)
